version: '3'

services:
  app:
    container_name: "reperio-core-ui-app"
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    ports: 
      - "8080:8080"
    volumes:
      - .:/opt/app
      - /opt/app/node_modules
      - /opt/app/dist
    command: ["yarn", "install-packages-then-start"]